[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
vote_delegate = "8a1coha6ryB3iXQxjBBEXNRGhMhi8u9xTnnGLLuzghEM"

[programs.mainnet]
vote_delegate = "8a1coha6ryB3iXQxjBBEXNRGhMhi8u9xTnnGLLuzghEM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/*"]
